## Website
title:              The Jekyde Blog
subtitle:           A static blog generator
host:               http://localhost

## Output
baseurl:            /
archive_dir:        archive
post_link:          post/:year/:month/:day/:name.html
page_link:          page/:name
paginate:           3

## Engine
latex:              true

## Server
port:               4040
